version: '3.8'
services:
  book_catalog:
    image: book_catal:latest
    build: 
      context: ./book_catalog
      dockerfile: Dockerfile
      args:
        - NO_CACHE=true
    container_name: book_catalog
    ports:
     - "4002:5000"
    environment:
      - PORT=5000
      - DATABASE_URL=postgresql://sit722_part4_m7u8_user:lCW453w9Dn8YgRKXofFAvbQVNp81Kvkm@dpg-crmf7d5umphs739d513g-a.oregon-postgres.render.com/sit722_part4_m7u8
    restart: "no"

  inventory_management:
    image: inventory_manage:latest
    build: 
      context: ./inventory_management
      dockerfile: Dockerfile
      args:
        - NO_CACHE=true
    container_name: inventory_management
    ports:
     - "4003:5001"
    environment:
      - PORT=5001
      - DATABASE_URL=postgresql://sit722_part4_m7u8_user:lCW453w9Dn8YgRKXofFAvbQVNp81Kvkm@dpg-crmf7d5umphs739d513g-a.oregon-postgres.render.com/sit722_part4_m7u8
    restart: "no"